language: c++

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x32 -extension GLX"
  - "export AUDIODEV=null"
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update

install:
  - sudo apt-get install haxe -y --force-yes
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install lime
  - haxelib install lime-tools
  - haxelib install openfl
  - haxelib install openfl-html5-dom
  - git clone https://github.com/ngrebenshikov/openfl-snapsvg ~/openfl-snapsvg --depth 1
  - haxelib dev openfl-snapsvg ~/openfl-snapsvg
  - git clone https://github.com/ngrebenshikov/openfl-snapsvg-tests ~/openfl-snapsvg-tests --depth 1

before_script:
  - cd ~/openfl-snapsvg-tests

script:
  - haxelib run munit test -js
