language: c++

addons:
  firefox: "19.0"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x32 -extension GLX"
  - "export AUDIODEV=null"
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update

install:
  - sudo apt-get install haxe -y --force-yes
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install lime 0.9.4
  - haxelib install lime-tools 1.2.9
  - haxelib install openfl 1.2.2
  - haxelib install openfl-html5-dom 1.2.1
  - haxelib install munit 2.1.0
  - git clone https://github.com/ngrebenshikov/openfl-snapsvg ~/openfl-snapsvg --depth 1
  - haxelib dev openfl-snapsvg ~/openfl-snapsvg
  - git clone https://github.com/ngrebenshikov/openfl-snapsvg-tests ~/openfl-snapsvg-tests --depth 1

before_script:
  - cd ~/openfl-snapsvg-tests
  - mkdir bin
  - mkdir bin/munit-resources
  - sleep 3

script:
  - haxelib run munit test -js -browser firefox -result-exit-code

after_script:
  - cat report/test/summary/js/summary.txt
